---
- hosts: omero-all
  roles:
    - role: ome.postgresql
      postgresql_databases:
        - name: omero
      postgresql_users:
        - user: omero
          password: omero
          databases: [omero]
      postgresql_version: "11"
    - role: ome.omero_server
      omero_server_rootpassword: ChangeMe
    - role: ome.omero_web
