---

- src: ome.upgrade_distpackages
  version: 1.1.3

- name: ome.certbot
  src: https://github.com/ome/ansible-role-certbot/archive/0.1.0.tar.gz
  version: 0.1.0

- src: ome.ssl_certificate
  version: 0.3.3

- src: ome.cli_utils
  version: 1.1.1

- src: ome.postgresql
  version: 5.2.0

- src: ome.omero_server
  version: 4.0.2

- src: ome.omero_web
  version: 4.0.1

- src: ome.omero_user
  version: 0.3.0

- src: ome.postgresql_backup
  version: 0.2.1

- name: ome.selinux_utils
  version: 1.0.3

- src: ome.redis
  version: 1.1.1

- src: ome.omero_web_django_prometheus
  version: 0.3.0
