---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-all
    image: centos/systemd
    image_version: latest
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../playbook.yml
  inventory:
    host_vars:
      omero-all:
        omero_server_systemd_require_network: false
        # Temporary workaround for
        # https://forum.image.sc/t/fyi-not-possible-to-create-new-omero-instance-with-latest-postgresql-versions/26929
        postgresql_package_version: 9.6.13
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
